total_change: int = int(input('Please enter an amount in cents between 0 and 99'))
quarters = int(total_change/25)
total_change = int(total_change - (quarters * 25))
dimes = int(total_change/10)
total_change = int(total_change - (dimes * 10))
nickels = int(total_change/5)
total_change = int(total_change - (nickels * 5))
pennies = int(total_change)

print('Your change is:')
print('Q: ' + str(quarters))
print('D: ' + str(dimes))
print('N: ' + str(nickels))
print('P: ' + str(pennies))
